version: '3'
services:
  go_dock:
    build:
      context: .
      dockerfile: .docker/golang/Dockerfile #ビルドに使用するDockerFileのディレクトリ
    tty: true # コンテナの起動永続化
    volumes:
      - ./:/go # マウントディレクトリ
    environment:
      - "GOPATH=/go"
      - "GO111MODULE=off" # モジュールはGOPATHを見にいく
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432